// packages/@markdown-ui/react/src/widgets/ButtonGroup.tsx
import React, { useState } from 'react';

export interface ButtonGroupProps {
  choices: string[];
  label?: string;
  default?: string;
  onchange: (value: string) => void;
}

export const ButtonGroup: React.FC<ButtonGroupProps> = ({ 
  choices, 
  label = '', 
  default: initial, 
  onchange 
}) => {
  const [selected, setSelected] = useState(initial ?? choices[0]);

  const handleClick = (choice: string) => {
    setSelected(choice);
    onchange(choice);
  };

  return (
    <div className="widget-button-group">
      {label && <label>{label}</label>}
      <div role="group" aria-label={label}>
        {choices.map((choice) => (
          <button
            key={choice}
            type="button"
            aria-pressed={selected === choice}
            onClick={() => handleClick(choice)}
          >
            {choice}
          </button>
        ))}
      </div>
    </div>
  );
};

// packages/@markdown-ui/svelte/src/lib/widgets/ButtonGroup.svelte
<script lang="ts">
  interface Props {
    choices: string[];
    label?: string;
    default?: string;
    onchange: (value: string) => void;
  }
  let { choices, label = '', default: initial, onchange }: Props = $props();
  let selected = $state(initial ?? choices[0]);
</script>

<div class="widget-button-group">
  {#if label}<label>{label}</label>{/if}
  <div role="group" aria-label={label}>
    {#each choices as c (c)}
      <button
        type="button"
        aria-pressed={selected === c}
        onclick={() => { selected = c; onchange(c); }}
      >
        {c}
      </button>
    {/each}
  </div>
</div>
