// packages/@markdown-ui/react/src/widgets/Form.tsx
import React, { useState } from 'react';
import { ButtonGroup } from './ButtonGroup';
import { Select } from './Select';
import { SelectMulti } from './SelectMulti';
import { Slider } from './Slider';
import { TextInput } from './TextInput';

export interface Field {
  type: string;
  id: string;
  [key: string]: any;
}

export interface FormProps {
  fields: Field[];
  submitLabel?: string;
  onchange: (values: Record<string, unknown>) => void;
}

export const Form: React.FC<FormProps> = ({ 
  fields, 
  submitLabel = 'Submit', 
  onchange 
}) => {
  const [data, setData] = useState<Record<string, unknown>>({});

  const setValue = (id: string, value: unknown) => {
    setData(prev => ({ ...prev, [id]: value }));
  };

  const handleSubmit = () => {
    onchange({ ...data });
  };

  const renderField = (field: Field) => {
    const commonProps = {
      ...field,
      onchange: (value: any) => setValue(field.id, value)
    };

    switch (field.type) {
      case 'button-group':
        return <ButtonGroup {...commonProps} choices={field.choices ?? []} />;
      case 'select':
        return <Select {...commonProps} choices={field.choices ?? []} />;
      case 'select-multi':
        return <SelectMulti {...commonProps} choices={field.choices ?? []} />;
      case 'slider':
        return (
          <Slider 
            {...commonProps} 
            min={field.min ?? 0} 
            max={field.max ?? 100} 
          />
        );
      case 'text-input':
        return <TextInput {...commonProps} />;
      default:
        return null;
    }
  };

  return (
    <div className="widget-form">
      {fields.map((field) => (
        <div key={field.id}>
          {renderField(field)}
        </div>
      ))}
      <button type="button" onClick={handleSubmit}>
        {submitLabel}
      </button>
    </div>
  );
};

// packages/@markdown-ui/svelte/src/lib/widgets/Form.svelte
<script lang="ts">
	import ButtonGroup from './ButtonGroup.svelte';
	import Select from './Select.svelte';
	import SelectMulti from './SelectMulti.svelte';
	import Slider from './Slider.svelte';
	import TextInput from './TextInput.svelte';

  interface Field {
    type: string;
    id: string;
    [key: string]: any;
  }
  interface Props {
    fields: Field[];
    submitLabel?: string;
    onchange: (values: Record<string, unknown>) => void;
  }
  let { fields, submitLabel = 'Submit', onchange }: Props = $props();

  // local state keyed by id
  const data = $state<Record<string, unknown>>({});
  function set(id: string, value: unknown) {
    data[id] = value;
  }

  function submit() {
    onchange({ ...data });
  }
</script>

<div class="widget-form">
  {#each fields as f (f.id)}
    {#if f.type === 'button-group'}
      <ButtonGroup {...f} choices={f.choices ?? []} onchange={(v) => set(f.id, v)} />
    {:else if f.type === 'select'}
      <Select {...f} choices={f.choices ?? []} onchange={(v) => set(f.id, v)} />
    {:else if f.type === 'select-multi'}
      <SelectMulti {...f} choices={f.choices ?? []} onchange={(v) => set(f.id, v)} />
    {:else if f.type === 'slider'}
      <Slider
        {...f}
        min={f.min ?? 0}
        max={f.max ?? 100}
        onchange={(v) => set(f.id, v)}
      />
    {:else if f.type === 'text-input'}
      <TextInput {...f} onchange={(v) => set(f.id, v)} />
    {/if}
  {/each}

  <button type="button" onclick={submit}>{submitLabel}</button>
</div>
