// packages/@markdown-ui/react/src/widgets/MultipleChoiceQuestion.tsx
import React, { useState } from 'react';

export interface MultipleChoiceQuestionProps {
  question: string;
  choices: string[];
  correctAnswer?: string;
  showFeedback?: boolean;
  onchange: (value: { answer: string; isCorrect?: boolean }) => void;
}

export const MultipleChoiceQuestion: React.FC<MultipleChoiceQuestionProps> = ({ 
  question, 
  choices, 
  correctAnswer,
  showFeedback = false,
  onchange 
}) => {
  const [selectedAnswer, setSelectedAnswer] = useState<string>('');
  const [hasAnswered, setHasAnswered] = useState(false);

  const handleAnswerSelect = (answer: string) => {
    setSelectedAnswer(answer);
    setHasAnswered(true);
    
    const isCorrect = correctAnswer ? answer === correctAnswer : undefined;
    onchange({ answer, isCorrect });
  };

  const getChoiceClassName = (choice: string) => {
    let className = 'mcq-choice';
    
    if (hasAnswered && showFeedback && correctAnswer) {
      if (choice === correctAnswer) {
        className += ' mcq-choice-correct';
      } else if (choice === selectedAnswer && choice !== correctAnswer) {
        className += ' mcq-choice-incorrect';
      }
    } else if (choice === selectedAnswer) {
      className += ' mcq-choice-selected';
    }
    
    return className;
  };

  return (
    <div className="widget-mcq">
      <div className="mcq-question">{question}</div>
      <div className="mcq-choices">
        {choices.map((choice, index) => (
          <button
            key={index}
            className={getChoiceClassName(choice)}
            onClick={() => handleAnswerSelect(choice)}
            disabled={hasAnswered && showFeedback}
          >
            {choice}
          </button>
        ))}
      </div>
      {hasAnswered && showFeedback && selectedAnswer && (
        <div className={`mcq-feedback ${selectedAnswer === correctAnswer ? 'correct' : 'incorrect'}`}>
          {correctAnswer ? 
            (selectedAnswer === correctAnswer ? '✓ Correct!' : `✗ Incorrect. The correct answer is: ${correctAnswer}`) :
            `You selected: ${selectedAnswer}`
          }
        </div>
      )}
    </div>
  );
};

// packages/@markdown-ui/svelte/src/lib/widgets/MultipleChoiceQuestion.svelte
<script lang="ts">
  interface Props {
    question: string;
    choices: string[];
    correctAnswer?: string;
    showFeedback?: boolean;
    onchange: (value: { answer: string; isCorrect?: boolean }) => void;
  }
  let { question, choices, correctAnswer = undefined, showFeedback = false, onchange }: Props = $props();
  let selectedAnswer = $state('');
  let hasAnswered = $state(false);

  function onSelect(answer: string) {
    selectedAnswer = answer;
    hasAnswered = true;
    const isCorrect = correctAnswer ? answer === correctAnswer : undefined;
    onchange({ answer, isCorrect });
  }

  function choiceClass(choice: string) {
    let cls = 'mcq-choice';
    if (hasAnswered && showFeedback && correctAnswer) {
      if (choice === correctAnswer) cls += ' mcq-choice-correct';
      else if (choice === selectedAnswer && choice !== correctAnswer) cls += ' mcq-choice-incorrect';
    } else if (choice === selectedAnswer) {
      cls += ' mcq-choice-selected';
    }
    return cls;
  }
</script>

<div class="widget-mcq">
  <div class="mcq-question">{question}</div>
  <div class="mcq-choices">
    {#each choices as choice, idx}
      <button
        class={choiceClass(choice)}
        onclick={() => onSelect(choice)}
        disabled={hasAnswered && showFeedback}
      >{choice}</button>
    {/each}
  </div>
  {#if hasAnswered && showFeedback && selectedAnswer}
    <div class={`mcq-feedback ${selectedAnswer === correctAnswer ? 'correct' : 'incorrect'}`}>
      {#if correctAnswer}
        {selectedAnswer === correctAnswer ? '✓ Correct!' : `✗ Incorrect. The correct answer is: ${correctAnswer}`}
      {:else}
        You selected: {selectedAnswer}
      {/if}
    </div>
  {/if}
  
</div>
