// packages/@markdown-ui/react/src/widgets/Quiz.tsx
import React, { useState, useMemo } from 'react';

export interface QuizProps {
  title: string;
  questions: QuizQuestion[];
  showScore?: boolean;
  showProgress?: boolean;
  passingScore?: number;
  onchange: (value: QuizState) => void;
}

interface QuizQuestion {
  id: string;
  type: "mcq" | "short-answer";
  question: string;
  points: number;
  // MCQ specific
  choices?: string[];
  correctAnswer?: string;
  // Short answer specific  
  placeholder?: string;
  correctAnswers?: string[];
}

interface QuizAnswer {
  answer: string;
  isCorrect: boolean;
  points: number;
  submitted: boolean;
}

interface QuizState {
  answers: Record<string, QuizAnswer>;
  totalScore: number;
  maxScore: number;
  questionsAnswered: number;
  isCompleted: boolean;
}

export const Quiz: React.FC<QuizProps> = ({ 
  title,
  questions,
  showScore = true,
  showProgress = true,
  passingScore,
  onchange 
}) => {
  const [answers, setAnswers] = useState<Record<string, QuizAnswer>>({});

  const quizState = useMemo<QuizState>(() => {
    const maxScore = questions.reduce((sum, q) => sum + q.points, 0);
    const totalScore = Object.values(answers).reduce((sum, a) => sum + a.points, 0);
    const questionsAnswered = Object.keys(answers).length;
    const isCompleted = questionsAnswered === questions.length;

    return {
      answers,
      totalScore,
      maxScore,
      questionsAnswered,
      isCompleted
    };
  }, [answers, questions]);

  const handleQuestionAnswer = (questionId: string, userAnswer: string) => {
    const question = questions.find(q => q.id === questionId);
    if (!question || answers[questionId]?.submitted) return;

    let isCorrect = false;
    
    if (question.type === "mcq") {
      isCorrect = question.correctAnswer === userAnswer;
    } else if (question.type === "short-answer") {
      if (question.correctAnswers) {
        isCorrect = question.correctAnswers.some(
          correct => correct.toLowerCase() === userAnswer.toLowerCase()
        );
      }
    }

    const newAnswer: QuizAnswer = {
      answer: userAnswer,
      isCorrect,
      points: isCorrect ? question.points : 0,
      submitted: true
    };

    const newAnswers = { ...answers, [questionId]: newAnswer };
    setAnswers(newAnswers);

    // Trigger onChange with updated state
    const updatedState = {
      answers: newAnswers,
      totalScore: Object.values(newAnswers).reduce((sum, a) => sum + a.points, 0),
      maxScore: quizState.maxScore,
      questionsAnswered: Object.keys(newAnswers).length,
      isCompleted: Object.keys(newAnswers).length === questions.length
    };

    onchange(updatedState);
  };

  const getProgressPercentage = () => {
    return Math.round((quizState.questionsAnswered / questions.length) * 100);
  };

  const getScorePercentage = () => {
    return quizState.maxScore > 0 ? Math.round((quizState.totalScore / quizState.maxScore) * 100) : 0;
  };

  const isPassing = () => {
    return passingScore ? getScorePercentage() >= passingScore : null;
  };

  const renderMCQQuestion = (question: QuizQuestion) => {
    const answer = answers[question.id];
    const isAnswered = answer?.submitted;

    return (
      <div key={question.id} className="quiz-question">
        <div className="quiz-question-header">
          <h3 className="quiz-question-text">{question.question}</h3>
          <span className="quiz-question-points">{question.points} pts</span>
        </div>
        
        <div className="quiz-choices">
          {question.choices?.map((choice, index) => {
            let choiceClass = 'quiz-choice';
            
            if (isAnswered) {
              if (choice === question.correctAnswer) {
                choiceClass += ' quiz-choice-correct';
              } else if (choice === answer.answer && choice !== question.correctAnswer) {
                choiceClass += ' quiz-choice-incorrect';
              }
            } else if (choice === answer?.answer) {
              choiceClass += ' quiz-choice-selected';
            }

            return (
              <button
                key={index}
                className={choiceClass}
                onClick={() => handleQuestionAnswer(question.id, choice)}
                disabled={isAnswered}
              >
                {choice}
              </button>
            );
          })}
        </div>

        {isAnswered && (
          <div className={`quiz-feedback ${answer.isCorrect ? 'correct' : 'incorrect'}`}>
            {answer.isCorrect 
              ? `✓ Correct! (+${answer.points} pts)` 
              : `✗ Incorrect. The correct answer is: ${question.correctAnswer}`}
          </div>
        )}
      </div>
    );
  };

  const renderShortAnswerQuestion = (question: QuizQuestion) => {
    const answer = answers[question.id];
    const isAnswered = answer?.submitted;
    const [inputValue, setInputValue] = useState('');

    const handleSubmit = () => {
      if (!inputValue.trim() || isAnswered) return;
      handleQuestionAnswer(question.id, inputValue.trim());
    };

    const handleKeyDown = (e: React.KeyboardEvent) => {
      if (e.key === 'Enter' && !isAnswered) {
        handleSubmit();
      }
    };

    return (
      <div key={question.id} className="quiz-question">
        <div className="quiz-question-header">
          <h3 className="quiz-question-text">{question.question}</h3>
          <span className="quiz-question-points">{question.points} pts</span>
        </div>
        
        <div className="quiz-input-container">
          <input
            type="text"
            value={isAnswered ? answer.answer : inputValue}
            onChange={(e) => !isAnswered && setInputValue(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder={question.placeholder || "Type your answer here..."}
            disabled={isAnswered}
            className={`quiz-input ${
              isAnswered 
                ? answer.isCorrect ? 'quiz-input-correct' : 'quiz-input-incorrect'
                : ''
            }`}
          />
          {!isAnswered && (
            <button 
              onClick={handleSubmit} 
              disabled={!inputValue.trim()}
              className="quiz-submit"
            >
              Submit
            </button>
          )}
        </div>

        {isAnswered && (
          <div className={`quiz-feedback ${answer.isCorrect ? 'correct' : 'incorrect'}`}>
            {answer.isCorrect 
              ? `✓ Correct! (+${answer.points} pts)` 
              : `✗ Incorrect. Accepted answers: ${question.correctAnswers?.join(', ') || 'N/A'}`}
          </div>
        )}
      </div>
    );
  };

  return (
    <div className="widget-quiz">
      {/* Quiz Header */}
      <div className="quiz-header">
        <h2 className="quiz-title">{title}</h2>
        
        <div className="quiz-stats">
          {showProgress && (
            <div className="quiz-progress">
              <span className="quiz-progress-text">
                Progress: {quizState.questionsAnswered}/{questions.length} questions
              </span>
              <div className="quiz-progress-bar">
                <div 
                  className="quiz-progress-fill"
                  style={{ width: `${getProgressPercentage()}%` }}
                />
              </div>
            </div>
          )}
          
          {showScore && (
            <div className="quiz-score">
              <span className="quiz-score-text">
                Score: {quizState.totalScore}/{quizState.maxScore} ({getScorePercentage()}%)
              </span>
            </div>
          )}
        </div>
      </div>

      {/* Questions */}
      <div className="quiz-questions">
        {questions.map((question) => 
          question.type === "mcq" 
            ? renderMCQQuestion(question)
            : renderShortAnswerQuestion(question)
        )}
      </div>

      {/* Quiz Summary */}
      {quizState.isCompleted && (
        <div className="quiz-summary">
          <h3>Quiz Complete!</h3>
          <div className="quiz-final-score">
            Final Score: {quizState.totalScore}/{quizState.maxScore} points ({getScorePercentage()}%)
          </div>
          {passingScore && (
            <div className={`quiz-result ${isPassing() ? 'passed' : 'failed'}`}>
              {isPassing() ? '🎉 Passed!' : '❌ Failed'} 
              (Passing: {passingScore}%)
            </div>
          )}
        </div>
      )}
    </div>
  );
};

// packages/@markdown-ui/svelte/src/lib/widgets/Quiz.svelte
<script lang="ts">
  interface QuizQuestion {
    id: string;
    type: 'mcq' | 'short-answer';
    question: string;
    points: number;
    choices?: string[];
    correctAnswer?: string;
    placeholder?: string;
    correctAnswers?: string[];
  }

  interface QuizAnswer {
    answer: string;
    isCorrect: boolean;
    points: number;
    submitted: boolean;
  }

  interface QuizState {
    answers: Record<string, QuizAnswer>;
    totalScore: number;
    maxScore: number;
    questionsAnswered: number;
    isCompleted: boolean;
  }

  interface Props {
    title: string;
    questions: QuizQuestion[];
    showScore?: boolean;
    showProgress?: boolean;
    passingScore?: number;
    onchange: (value: QuizState) => void;
  }

  let { title, questions, showScore = true, showProgress = true, passingScore = undefined, onchange }: Props = $props();

  let answers = $state<Record<string, QuizAnswer>>({});
  let draftInputs = $state<Record<string, string>>({});

  const maxScore = $derived(questions.reduce((s, q) => s + q.points, 0));
  const totalScore = $derived(Object.values(answers).reduce((s, a) => s + a.points, 0));
  const questionsAnswered = $derived(Object.keys(answers).length);
  const isCompleted = $derived(questionsAnswered === questions.length);
  const progressPercentage = $derived(Math.round((questionsAnswered / questions.length) * 100));
  const scorePercentage = $derived(maxScore > 0 ? Math.round((totalScore / maxScore) * 100) : 0);
  const isPassing = $derived(passingScore !== undefined ? scorePercentage >= (passingScore as number) : false);

  function emitChange() {
    onchange({
      answers: { ...answers },
      totalScore,
      maxScore,
      questionsAnswered,
      isCompleted
    });
  }

  function onAnswer(questionId: string, userAnswer: string) {
    const q = questions.find(q => q.id === questionId);
    if (!q || answers[questionId]?.submitted) return;

    let correct = false;
    if (q.type === 'mcq') {
      correct = q.correctAnswer === userAnswer;
    } else if (q.type === 'short-answer') {
      if (q.correctAnswers) {
        correct = q.correctAnswers.some(a => a.toLowerCase() === userAnswer.toLowerCase());
      }
    }

    answers = { ...answers, [questionId]: { answer: userAnswer, isCorrect: correct, points: correct ? q.points : 0, submitted: true } };
    if (draftInputs[questionId]) {
      const { [questionId]: _, ...rest } = draftInputs; // remove draft
      draftInputs = rest;
    }
    emitChange();
  }

  function submitShort(q: QuizQuestion) {
    const val = (draftInputs[q.id] || '').trim();
    if (!val) return;
    onAnswer(q.id, val);
  }

  function mcqChoiceClass(q: QuizQuestion, choice: string) {
    const ans = answers[q.id];
    let cls = 'quiz-choice';
    if (ans?.submitted) {
      if (choice === q.correctAnswer) cls += ' quiz-choice-correct';
      else if (choice === ans.answer && choice !== q.correctAnswer) cls += ' quiz-choice-incorrect';
    }
    return cls;
  }
</script>

<div class="widget-quiz">
  <div class="quiz-header">
    <h2 class="quiz-title">{title}</h2>
    <div class="quiz-stats">
      {#if showProgress}
        <div class="quiz-progress">
          <span class="quiz-progress-text">Progress: {questionsAnswered}/{questions.length} questions</span>
          <div class="quiz-progress-bar">
            <div class="quiz-progress-fill" style={`width: ${progressPercentage}%`}></div>
          </div>
        </div>
      {/if}
      {#if showScore}
        <div class="quiz-score">
          <span class="quiz-score-text">Score: {totalScore}/{maxScore} ({scorePercentage}%)</span>
        </div>
      {/if}
    </div>
  </div>

  <div class="quiz-questions">
    {#each questions as q}
      {#if q.type === 'mcq'}
        <div class="quiz-question">
          <div class="quiz-question-header">
            <h3 class="quiz-question-text">{q.question}</h3>
            <span class="quiz-question-points">{q.points} pts</span>
          </div>
          <div class="quiz-choices">
            {#each q.choices || [] as choice, idx}
              <button class={mcqChoiceClass(q, choice)} onclick={() => onAnswer(q.id, choice)} disabled={answers[q.id]?.submitted}>{choice}</button>
            {/each}
          </div>
          {#if answers[q.id]?.submitted}
            <div class={`quiz-feedback ${answers[q.id].isCorrect ? 'correct' : 'incorrect'}`}>
              {answers[q.id].isCorrect ? `✓ Correct! (+${answers[q.id].points} pts)` : `✗ Incorrect. The correct answer is: ${q.correctAnswer}`}
            </div>
          {/if}
        </div>
      {:else}
        <div class="quiz-question">
          <div class="quiz-question-header">
            <h3 class="quiz-question-text">{q.question}</h3>
            <span class="quiz-question-points">{q.points} pts</span>
          </div>
          <div class="quiz-input-container">
            <input
              type="text"
              value={answers[q.id]?.submitted ? answers[q.id].answer : (draftInputs[q.id] || '')}
              oninput={(e) => { if (!answers[q.id]?.submitted) draftInputs[q.id] = (e.target as HTMLInputElement).value; }}
              onkeydown={(e) => { if (e.key === 'Enter' && !answers[q.id]?.submitted) submitShort(q); }}
              placeholder={q.placeholder || 'Type your answer here...'}
              disabled={answers[q.id]?.submitted}
              class={`quiz-input ${answers[q.id]?.submitted ? (answers[q.id].isCorrect ? 'quiz-input-correct' : 'quiz-input-incorrect') : ''}`}
            />
            {#if !answers[q.id]?.submitted}
              <button class="quiz-submit" onclick={() => submitShort(q)} disabled={!((draftInputs[q.id] || '').trim())}>Submit</button>
            {/if}
          </div>
          {#if answers[q.id]?.submitted}
            <div class={`quiz-feedback ${answers[q.id].isCorrect ? 'correct' : 'incorrect'}`}>
              {answers[q.id].isCorrect ? `✓ Correct! (+${answers[q.id].points} pts)` : `✗ Incorrect. Accepted answers: ${(q.correctAnswers || []).join(', ') || 'N/A'}`}
            </div>
          {/if}
        </div>
      {/if}
    {/each}
  </div>

  {#if isCompleted}
    <div class="quiz-summary">
      <h3>Quiz Complete!</h3>
      <div class="quiz-final-score">Final Score: {totalScore}/{maxScore} points ({scorePercentage}%)</div>
      {#if passingScore !== undefined}
        <div class={`quiz-result ${isPassing ? 'passed' : 'failed'}`}>
          {isPassing ? '🎉 Passed!' : '❌ Failed'} (Passing: {passingScore}%)
        </div>
      {/if}
    </div>
  {/if}
</div>
