// packages/@markdown-ui/react/src/widgets/Slider.tsx
import React, { useState } from 'react';

export interface SliderProps {
  min: number;
  max: number;
  step?: number;
  label?: string;
  default?: number;
  onchange: (value: number) => void;
}

export const Slider: React.FC<SliderProps> = ({ 
  min, 
  max, 
  step = 1, 
  label = '', 
  default: initial = min, 
  onchange 
}) => {
  const [value, setValue] = useState(initial);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newValue = Number(e.target.value);
    setValue(newValue);
  };

  const handleComplete = () => {
    onchange(value);
  };

  return (
    <div className="widget-slider">
      {label && <label>{label}</label>}
      <div className="slider-container">
        <div className="slider-values">
          <span className="min-value">{min}</span>
          <span className="current-value">{value}</span>
          <span className="max-value">{max}</span>
        </div>
        <input
          type="range"
          value={value}
          min={min}
          max={max}
          step={step}
          onChange={handleChange}
          onMouseUp={handleComplete}
          onTouchEnd={handleComplete}
        />
      </div>
    </div>
  );
};

// packages/@markdown-ui/svelte/src/lib/widgets/Slider.svelte
<script lang="ts">
  interface Props {
    min: number;
    max: number;
    step?: number;
    label?: string;
    default?: number;
    onchange: (value: number) => void;
  }
  let { min, max, step = 1, label = '', default: initial = min, onchange }: Props = $props();
  let value = $state(initial);
</script>

<div class="widget-slider">
  {#if label}<label>{label}</label>{/if}
  <div class="slider-container">
    <div class="slider-values">
      <span class="min-value">{min}</span>
      <span class="current-value">{value}</span>
      <span class="max-value">{max}</span>
    </div>
    <input
      type="range"
      bind:value
      {min}
      {max}
      {step}
      onmouseup={() => onchange(value)}
      ontouchend={() => onchange(value)}
    />
  </div>
</div>
