// packages/@markdown-ui/svelte/src/lib/widgets/ShortAnswerQuestion.svelte
<script lang="ts">
  interface Props {
    question: string;
    placeholder?: string;
    correctAnswer?: string;
    correctAnswers?: string[];
    showFeedback?: boolean;
    onchange: (value: { answer: string; isCorrect?: boolean }) => void;
  }
  let { question, placeholder = 'Type your answer here...', correctAnswer = undefined, correctAnswers = undefined, showFeedback = false, onchange }: Props = $props();
  let answer = $state('');
  let hasAnswered = $state(false);
  let isCorrect: boolean | undefined = $state(undefined);

  function submit() {
    const val = answer.trim();
    if (!val) return;
    hasAnswered = true;
    const normalized = (correctAnswers && correctAnswers.length > 0) ? correctAnswers : (correctAnswer !== undefined ? [correctAnswer] : undefined);
    const correct = normalized ? normalized.some(a => a.toLowerCase() === val.toLowerCase()) : undefined;
    isCorrect = correct;
    onchange({ answer: val, isCorrect: correct });
  }

  function feedbackMessage() {
    if (!hasAnswered || !showFeedback) return '';
    const hasAnswers = (correctAnswers && correctAnswers.length > 0) || (correctAnswer !== undefined);
    if (!hasAnswers) return `Your answer: ${answer.trim()}`;
    if (correctAnswers && correctAnswers.length > 0) {
      return isCorrect ? '✓ Correct!' : `✗ Incorrect. Accepted answers: ${(correctAnswers || []).join(', ')}`;
    }
    return isCorrect ? '✓ Correct!' : `✗ Incorrect. The correct answer is: ${correctAnswer}`;
  }
</script>

<div class="widget-saq">
  <div class="saq-question">{question}</div>
  <div class="saq-input-container">
    <input
      type="text"
      bind:value={answer}
      {placeholder}
      onkeydown={(e) => { if (e.key === 'Enter' && !hasAnswered) submit(); }}
      disabled={hasAnswered && showFeedback}
      class={`saq-input ${hasAnswered && showFeedback ? (isCorrect ? 'saq-input-correct' : 'saq-input-incorrect') : ''}`}
    />
    {#if !hasAnswered}
      <button class="saq-submit" onclick={submit} disabled={!answer.trim()}>Submit</button>
    {/if}
  </div>
  {#if hasAnswered && showFeedback && feedbackMessage()}
    <div class={`saq-feedback ${isCorrect ? 'correct' : 'incorrect'}`}>{feedbackMessage()}</div>
  {/if}
</div>

// packages/@markdown-ui/vue/src/lib/widgets/ShortAnswerQuestion.vue
<template>
  <div class="widget-saq">
    <div class="saq-question">{{ question }}</div>
    <div class="saq-input-container">
      <input
        type="text"
        v-model="answer"
        :placeholder="placeholder || 'Type your answer here...'"
        :disabled="hasAnswered && showFeedback"
        :class="['saq-input', (hasAnswered && showFeedback) ? (isCorrect ? 'saq-input-correct' : 'saq-input-incorrect') : '']"
        @keydown.enter.prevent="!hasAnswered && submit()"
      />
      <button
        v-if="!hasAnswered"
        class="saq-submit"
        :disabled="!answer.trim()"
        @click="submit"
      >
        Submit
      </button>
    </div>
    <div
      v-if="hasAnswered && showFeedback && feedbackMessage"
      :class="['saq-feedback', isCorrect ? 'correct' : 'incorrect']"
    >
      {{ feedbackMessage }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, withDefaults, defineProps, defineEmits } from 'vue'

interface Props {
  question: string
  placeholder?: string
  correctAnswer?: string
  correctAnswers?: string[]
  showFeedback?: boolean
}

interface Emits {
  change: [value: { answer: string; isCorrect?: boolean }]
}

const props = withDefaults(defineProps<Props>(), {
  placeholder: 'Type your answer here...',
  showFeedback: false
})

const emit = defineEmits<Emits>()

const answer = ref('')
const hasAnswered = ref(false)
const isCorrect = ref<boolean | undefined>(undefined)

function submit() {
  if (!answer.value.trim()) return
  hasAnswered.value = true
  const normalized = (props.correctAnswers && props.correctAnswers.length > 0)
    ? props.correctAnswers
    : (typeof props.correctAnswer === 'string' ? [props.correctAnswer] : undefined)
  const correct = normalized
    ? normalized.some(a => a.toLowerCase() === answer.value.trim().toLowerCase())
    : undefined
  isCorrect.value = correct
  emit('change', { answer: answer.value.trim(), isCorrect: correct })
}

const feedbackMessage = computed(() => {
  if (!hasAnswered.value || !props.showFeedback) return ''
  const hasAnswers = (props.correctAnswers && props.correctAnswers.length > 0) || typeof props.correctAnswer !== 'undefined'
  if (!hasAnswers) return `Your answer: ${answer.value.trim()}`
  if (props.correctAnswers && props.correctAnswers.length > 0) {
    return isCorrect.value ? '✓ Correct!' : `✗ Incorrect. Accepted answers: ${(props.correctAnswers || []).join(', ')}`
  }
  return isCorrect.value ? '✓ Correct!' : `✗ Incorrect. The correct answer is: ${props.correctAnswer}`
})
</script>
