// packages/@markdown-ui/react/src/widgets/TextInput.tsx
import React, { useState } from 'react';

export interface TextInputProps {
  placeholder?: string;
  label?: string;
  default?: string;
  onchange: (value: string) => void;
}

export const TextInput: React.FC<TextInputProps> = ({ 
  placeholder = '', 
  label = '', 
  default: initial = '', 
  onchange 
}) => {
  const [value, setValue] = useState(initial);

  const handleBlur = () => {
    onchange(value);
  };

  return (
    <div className="widget-button">
      {label && <label>{label}</label>}
      <input
        type="text"
        value={value}
        onChange={(e) => setValue(e.target.value)}
        onBlur={handleBlur}
        placeholder={placeholder}
      />
    </div>
  );
};

// packages/@markdown-ui/vue/src/lib/widgets/TextInput.vue
<template>
  <div class="widget-button">
    <label v-if="label">{{ label }}</label>
    <input
      type="text"
      v-model="value"
      @blur="handleBlur"
      :placeholder="placeholder"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, defineProps, defineEmits } from 'vue'

interface TextInputProps {
  placeholder?: string
  label?: string
  default?: string
}

interface TextInputEvents {
  change: [value: string]
}

const props = withDefaults(defineProps<TextInputProps>(), {
  placeholder: '',
  label: '',
  default: ''
})

const emit = defineEmits<TextInputEvents>()

const value = ref(props.default)

const handleBlur = () => {
  emit('change', value.value)
}
</script>
