// packages/@markdown-ui/svelte/src/lib/widgets/Widget.svelte
<svelte:options
  customElement={{
    tag: 'markdown-ui-widget',
    shadow: 'none',            // use 'none' if you want light-DOM
    props: {
      id: {               // the prop you asked for
        type: 'String',        // treat incoming attribute as plain text
        attribute: 'id',  // <markdown-ui-widget content="…">
        reflect: true          // update the attribute if we change it
      },
      content: {               // the prop you asked for
        type: 'String',        // treat incoming attribute as plain text
        attribute: 'content',  // <markdown-ui-widget content="…">
        reflect: true          // update the attribute if we change it
      }
    }
  }}
/>

<script lang="ts">
  import * as widgets from './index.js';

  let { id, content } = $props();

  let parsed = { type: "incomplete" };

  try {
    parsed = JSON.parse(atob(content));
  } catch (e) {
    // suppress intermediate states
  }

  const Cmp    = widgets[parsed.type as keyof typeof widgets];

  function dispatch(detail: any) {
		$host().dispatchEvent(
      new CustomEvent('widget-event', {
        detail: detail,
        bubbles: true,
        composed: true   // let it cross the shadow-root boundary
      })
    );
	}
</script>

<div class="widget">
  {#if Cmp}
    <Cmp {...parsed} onchange={(value) => dispatch({id: id, value: value})}/>
  {:else}
    <span style="color:red">Unknown widget “{parsed.type}”</span>
  {/if}
</div>

// packages/@markdown-ui/vue/src/lib/widgets/Widget.vue
<template>
  <div class="widget">
    <component
      v-if="WidgetComponent"
      :is="WidgetComponent"
      v-bind="parsed"
      @change="(value) => dispatch({ id: props.id, value })"
    />
    <span v-else style="color: red">
      Unknown widget "{{ parsed.type }}"
    </span>
  </div>
</template>

<script setup lang="ts">
import { computed, defineProps } from 'vue'
import ButtonGroup from './ButtonGroup.vue'
import Form from './Form.vue'
import Incomplete from './Incomplete.vue'
import Select from './Select.vue'
import SelectMulti from './SelectMulti.vue'
import Slider from './Slider.vue'
import TextInput from './TextInput.vue'

interface WidgetProps {
  id: string
  content: string
}

const props = defineProps<WidgetProps>()

const widgets = {
  'ButtonGroup': ButtonGroup,
  'Form': Form,
  'Incomplete': Incomplete,
  'Select': Select,
  'SelectMulti': SelectMulti,
  'Slider': Slider,
  'TextInput': TextInput
}

const typeMapping: Record<string, keyof typeof widgets> = {
  'button-group': 'ButtonGroup',
  'form': 'Form',
  'incomplete': 'Incomplete',
  'select': 'Select',
  'select-multi': 'SelectMulti',
  'slider': 'Slider',
  'text-input': 'TextInput'
}

let parsed = { type: 'incomplete' }

try {
  parsed = JSON.parse(atob(props.content))
} catch (e) {
  // suppress intermediate states
}

const WidgetComponent = computed(() => {
  const componentType = typeMapping[parsed.type] || parsed.type
  return widgets[componentType as keyof typeof widgets]
})

const dispatch = (detail: any) => {
  const event = new CustomEvent('widget-event', {
    detail: detail,
    bubbles: true,
    composed: true
  })
  
  // Find the custom element and bubble up to find the closest widget container
  const customElement = document.querySelector(`markdown-ui-widget[id="${props.id}"]`)
  if (customElement) {
    const container = customElement.closest('.widget-container')
    if (container) {
      container.dispatchEvent(event)
    }
  }
}
</script>
