// packages/@markdown-ui/vue/src/lib/widgets/SelectMulti.vue
<template>
  <div class="selector-multi">
    <div v-if="label" class="selector-multi-label">{{ label }}</div>
    <div class="checkbox-group">
      <label v-for="choice in choices" :key="choice" class="checkbox-item">
        <input
          type="checkbox"
          :value="choice"
          :checked="value.includes(choice)"
          @change="handleChange"
        />
        <span>{{ choice }}</span>
      </label>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, defineProps, defineEmits } from 'vue'

interface SelectMultiProps {
  choices: string[]
  label?: string
  default?: string | string[]
}

interface SelectMultiEvents {
  change: [value: string | string[]]
}

const props = withDefaults(defineProps<SelectMultiProps>(), {
  label: ''
})

const emit = defineEmits<SelectMultiEvents>()

const value = ref<string[]>(
  Array.isArray(props.default) ? props.default : (props.default ? [props.default] : [])
)

const handleChange = (e: Event) => {
  const target = e.target as HTMLInputElement
  const choice = target.value
  
  if (target.checked) {
    value.value = [...value.value, choice]
  } else {
    value.value = value.value.filter(v => v !== choice)
  }
  
  emit('change', value.value)
}
</script>

// packages/@markdown-ui/react/src/widgets/SelectMulti.tsx
import React, { useState } from 'react';

export interface SelectMultiProps {
  choices: string[];
  label?: string;
  default?: string | string[];
  onchange: (value: string | string[]) => void;
}

export const SelectMulti: React.FC<SelectMultiProps> = ({ 
  choices, 
  label = '', 
  default: initial, 
  onchange 
}) => {
  const [value, setValue] = useState<string[]>(
    Array.isArray(initial) ? initial : (initial ? [initial] : [])
  );

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const choice = e.target.value;
    let newValue: string[];
    
    if (e.target.checked) {
      newValue = [...value, choice];
    } else {
      newValue = value.filter(v => v !== choice);
    }
    
    setValue(newValue);
    onchange(newValue);
  };

  return (
    <div className="selector-multi">
      {label && <div className="selector-multi-label">{label}</div>}
      <div className="checkbox-group">
        {choices.map((choice) => (
          <label key={choice} className="checkbox-item">
            <input
              type="checkbox"
              value={choice}
              checked={value.includes(choice)}
              onChange={handleChange}
            />
            <span>{choice}</span>
          </label>
        ))}
      </div>
    </div>
  );
};
