// src/lib/widgets/Select.svelte
<script lang="ts">
  interface Props {
    choices: string[];
    label?: string;
    default?: string;
    onchange: (value: string | string[]) => void;
  }
  let { choices, label = '', default: initial, onchange }: Props = $props();

  let val = $state(initial ?? choices[0]);
</script>

<div class="selector">
  {#if label}<label>{label}</label>{/if}
  <select bind:value={val} onchange={() => onchange(val)}>
    {#each choices as c (c)}
      <option value={c}>{c}</option>
    {/each}
  </select>
</div>

// packages/@markdown-ui/react/src/widgets/Select.tsx
import React, { useState } from 'react';

export interface SelectProps {
  choices: string[];
  label?: string;
  default?: string;
  onchange: (value: string | string[]) => void;
}

export const Select: React.FC<SelectProps> = ({ 
  choices, 
  label = '', 
  default: initial, 
  onchange 
}) => {
  const [value, setValue] = useState(initial ?? choices[0]);

  const handleChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const newValue = e.target.value;
    setValue(newValue);
    onchange(newValue);
  };

  return (
    <div className="selector">
      {label && <label>{label}</label>}
      <select value={value} onChange={handleChange}>
        {choices.map((choice) => (
          <option key={choice} value={choice}>
            {choice}
          </option>
        ))}
      </select>
    </div>
  );
};
