// packages/@markdown-ui/vue/src/lib/widgets/Select.vue
<template>
  <div class="selector">
    <label v-if="label">{{ label }}</label>
    <select v-model="value" @change="handleChange">
      <option v-for="choice in choices" :key="choice" :value="choice">
        {{ choice }}
      </option>
    </select>
  </div>
</template>

<script setup lang="ts">
import { ref, defineProps, defineEmits } from 'vue'

interface SelectProps {
  choices: string[]
  label?: string
  default?: string
}

interface SelectEvents {
  change: [value: string | string[]]
}

const props = withDefaults(defineProps<SelectProps>(), {
  label: ''
})

const emit = defineEmits<SelectEvents>()

const value = ref(props.default ?? props.choices[0])

const handleChange = () => {
  emit('change', value.value)
}
</script>

// packages/@markdown-ui/react/src/widgets/Select.tsx
import React, { useState } from 'react';

export interface SelectProps {
  choices: string[];
  label?: string;
  default?: string;
  onchange: (value: string | string[]) => void;
}

export const Select: React.FC<SelectProps> = ({ 
  choices, 
  label = '', 
  default: initial, 
  onchange 
}) => {
  const [value, setValue] = useState(initial ?? choices[0]);

  const handleChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const newValue = e.target.value;
    setValue(newValue);
    onchange(newValue);
  };

  return (
    <div className="selector">
      {label && <label>{label}</label>}
      <select value={value} onChange={handleChange}>
        {choices.map((choice) => (
          <option key={choice} value={choice}>
            {choice}
          </option>
        ))}
      </select>
    </div>
  );
};
