// packages/@markdown-ui/vue/src/lib/widgets/Slider.vue
<template>
  <div class="widget-slider">
    <label v-if="label">{{ label }}</label>
    <div class="slider-container">
      <div class="slider-values">
        <span class="min-value">{{ min }}</span>
        <span class="current-value">{{ value }}</span>
        <span class="max-value">{{ max }}</span>
      </div>
      <input
        type="range"
        v-model="value"
        :min="min"
        :max="max"
        :step="step"
        @mouseup="handleChange"
        @touchend="handleChange"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, defineProps, defineEmits } from 'vue'

interface SliderProps {
  min: number
  max: number
  step?: number
  label?: string
  default?: number
}

interface SliderEvents {
  change: [value: number]
}

const props = withDefaults(defineProps<SliderProps>(), {
  step: 1,
  label: ''
})

const emit = defineEmits<SliderEvents>()

const value = ref(props.default ?? props.min)

const handleChange = () => {
  emit('change', Number(value.value))
}
</script>

// packages/@markdown-ui/react/src/widgets/Slider.tsx
import React, { useState } from 'react';

export interface SliderProps {
  min: number;
  max: number;
  step?: number;
  label?: string;
  default?: number;
  onchange: (value: number) => void;
}

export const Slider: React.FC<SliderProps> = ({ 
  min, 
  max, 
  step = 1, 
  label = '', 
  default: initial = min, 
  onchange 
}) => {
  const [value, setValue] = useState(initial);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newValue = Number(e.target.value);
    setValue(newValue);
    onchange(newValue);
  };

  return (
    <div className="widget-slider">
      {label && <label>{label}</label>}
      <div className="slider-container">
        <div className="slider-values">
          <span className="min-value">{min}</span>
          <span className="current-value">{value}</span>
          <span className="max-value">{max}</span>
        </div>
        <input
          type="range"
          value={value}
          min={min}
          max={max}
          step={step}
          onChange={handleChange}
        />
      </div>
    </div>
  );
};
