// src/lib/widgets/Slider.svelte
<script lang="ts">
  interface Props {
    min: number;
    max: number;
    step?: number;
    label?: string;
    default?: number;
    onchange: (value: number) => void;
  }
  let { min, max, step = 1, label = '', default: initial = min, onchange }: Props = $props();
  let value = $state(initial);
</script>

<div class="widget-slider">
  {#if label}<label>{label}</label>{/if}
  <input
    type="range"
    bind:value
    {min}
    {max}
    {step}
    onchange={() => onchange(value)}
  />
</div>

// packages/@markdown-ui/react/src/widgets/Slider.tsx
import React, { useState } from 'react';

export interface SliderProps {
  min: number;
  max: number;
  step?: number;
  label?: string;
  default?: number;
  onchange: (value: number) => void;
}

export const Slider: React.FC<SliderProps> = ({ 
  min, 
  max, 
  step = 1, 
  label = '', 
  default: initial = min, 
  onchange 
}) => {
  const [value, setValue] = useState(initial);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newValue = Number(e.target.value);
    setValue(newValue);
    onchange(newValue);
  };

  return (
    <div className="widget-slider">
      {label && <label>{label}</label>}
      <input
        type="range"
        value={value}
        min={min}
        max={max}
        step={step}
        onChange={handleChange}
      />
    </div>
  );
};
