// src/lib/widgets/TextInput.svelte
<script lang="ts">
  interface Props {
    placeholder?: string;
    label?: string;
    default?: string;
    onchange: (value: string) => void;
  }
  let { placeholder = '', label = '', default: initial = '', onchange }: Props = $props();
  let value = $state(initial);
</script>

<div class="widget-button">
  {#if label}<label>{label}</label>{/if}
  <input
    type="text"
    bind:value
    {placeholder}
    onfocusout={() => onchange(value)}
  />
</div>

// packages/@markdown-ui/react/src/widgets/TextInput.tsx
import React, { useState } from 'react';

export interface TextInputProps {
  placeholder?: string;
  label?: string;
  default?: string;
  onchange: (value: string) => void;
}

export const TextInput: React.FC<TextInputProps> = ({ 
  placeholder = '', 
  label = '', 
  default: initial = '', 
  onchange 
}) => {
  const [value, setValue] = useState(initial);

  const handleBlur = () => {
    onchange(value);
  };

  return (
    <div className="widget-button">
      {label && <label>{label}</label>}
      <input
        type="text"
        value={value}
        onChange={(e) => setValue(e.target.value)}
        onBlur={handleBlur}
        placeholder={placeholder}
      />
    </div>
  );
};
