// packages/@markdown-ui/vue/src/lib/widgets/Widget.vue
<template>
  <div class="widget">
    <component
      v-if="WidgetComponent"
      :is="WidgetComponent"
      v-bind="parsed"
      @change="(value) => dispatch({ id: props.id, value })"
    />
    <span v-else style="color: red">
      Unknown widget "{{ parsed.type }}"
    </span>
  </div>
</template>

<script setup lang="ts">
import { computed, defineProps } from 'vue'
import ButtonGroup from './ButtonGroup.vue'
import Form from './Form.vue'
import Incomplete from './Incomplete.vue'
import Select from './Select.vue'
import SelectMulti from './SelectMulti.vue'
import Slider from './Slider.vue'
import TextInput from './TextInput.vue'

interface WidgetProps {
  id: string
  content: string
}

const props = defineProps<WidgetProps>()

const widgets = {
  'ButtonGroup': ButtonGroup,
  'Form': Form,
  'Incomplete': Incomplete,
  'Select': Select,
  'SelectMulti': SelectMulti,
  'Slider': Slider,
  'TextInput': TextInput
}

const typeMapping: Record<string, keyof typeof widgets> = {
  'button-group': 'ButtonGroup',
  'form': 'Form',
  'incomplete': 'Incomplete',
  'select': 'Select',
  'select-multi': 'SelectMulti',
  'slider': 'Slider',
  'text-input': 'TextInput'
}

let parsed = { type: 'incomplete' }

try {
  parsed = JSON.parse(atob(props.content))
} catch (e) {
  // suppress intermediate states
}

const WidgetComponent = computed(() => {
  const componentType = typeMapping[parsed.type] || parsed.type
  return widgets[componentType as keyof typeof widgets]
})

const dispatch = (detail: any) => {
  const event = new CustomEvent('widget-event', {
    detail: detail,
    bubbles: true,
    composed: true
  })
  
  // Find the custom element and bubble up to find the closest widget container
  const customElement = document.querySelector(`markdown-ui-widget[id="${props.id}"]`)
  if (customElement) {
    const container = customElement.closest('.widget-container')
    if (container) {
      container.dispatchEvent(event)
    }
  }
}
</script>

// packages/@markdown-ui/react/src/widgets/Widget.tsx
import React, { useEffect } from 'react';
import * as widgets from './index';

export interface WidgetProps {
  id: string;
  content: string;
}

type WidgetType = keyof typeof widgets;

// Map camelCase JSON types to PascalCase component names
const typeMapping: Record<string, WidgetType> = {
  'button-group': 'ButtonGroup',
  'form': 'Form',
  'incomplete': 'Incomplete',
  'select': 'Select',
  'select-multi': 'SelectMulti',
  'slider': 'Slider',
  'text-input': 'TextInput'
};

export const Widget: React.FC<WidgetProps> = ({ id, content }) => {
  const parsed = JSON.parse(atob(content));
  const componentType = typeMapping[parsed.type] || parsed.type;
  const WidgetComponent = widgets[componentType as WidgetType];

  const dispatch = (detail: any) => {
    const event = new CustomEvent('widget-event', {
      detail: detail,
      bubbles: true,
      composed: true
    });
    
    // Find the custom element and bubble up to find the closest widget container
    const customElement = document.querySelector(`markdown-ui-widget[id="${id}"]`);
    if (customElement) {
      const container = customElement.closest('.widget-container');
      if (container) {
        container.dispatchEvent(event);
      }
    }
  };

  if (!WidgetComponent) {
    return (
      <div className="widget">
        <span style={{ color: 'red' }}>
          Unknown widget "{parsed.type}"
        </span>
      </div>
    );
  }

  return (
    <div className="widget">
      <WidgetComponent 
        {...parsed} 
        onchange={(value: any) => dispatch({ id, value })} 
      />
    </div>
  );
};
